#!/bin/sh

which gpg-agent &>/dev/null || return

# Start the GnuPG agent and enable OpenSSH agent emulation
gnupginf="${HOME}/.gnupg/gpg-agent.info"

if pgrep -u "${USER}" gpg-agent >/dev/null 2>&1; then
    eval $(cat $gnupginf)
    eval $(cut -d= -f1 $gnupginf | xargs echo export)
else
    eval $(gpg-agent --enable-ssh-support --daemon --write-env-file ${gnupginf})
fi

GPG_TTY=$(tty)
export GPG_TTY
