#! /bin/sh
# colors
for dircolors in gdircolors dircolors ; do
	if command -v $dircolors >/dev/null 2>&1 ; then
		dircolor_text=''
		if [ -f "${HOME}/.dir_colors" ] ; then
			dircolor_text=`cat "${HOME}/.dir_colors"`
		elif [ -f /etc/DIR_COLORS ] ; then
			dircolor_text=`cat /etc/DIR_COLORS`
		fi

		if $dircolors --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			dircolor_text="${dircolor_text}\nSTICKY_OTHER_WRITABLE 01;04;34;40"
			dircolor_text="${dircolor_text}\nOTHER_WRITABLE 01;34;40"
		fi

		eval `echo "${dircolor_text}" | $dircolors -b -`
		break
	fi
done

# gimmie an editor, make it a nice vi clone
for EDITOR in vimx vim elvis vile nvi vi ; do
	command -v $EDITOR >/dev/null 2>&1 && break
done
export EDITOR

# make the history editor the editor we want
FCEDIT=$EDITOR
export FCEDIT

# vimx -> vim
if [ "${EDITOR}" = vimx ] ; then
	alias vim=vimx
fi

# aliases
alias cd..='cd ..'

# handles per OS aliases, fixes a few terms
case `uname -s` in
	Linux|CYGWIN*)
		alias ls="ls -h --color=auto"
		alias grep='grep -d skip --color=auto'
	;;
	FreeBSD|Darwin|DragonFly)
		if command -v top >/dev/null 2>&1 ; then
			alias top="top -o cpu"
		fi

		if command -v gls >/dev/null 2>&1 ; then
			alias ls="gls -h --color=auto"
		elif ls --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias ls="ls -h --color=auto"
		else
			LSCOLORS="ExGxFxDxCxDxDxHbaDEaEa"
			export LSCOLORS
			alias ls="ls -Gh"
		fi
		alias grep='grep -d skip --color=auto'
	;;
	Interix)
		alias ls="ls --color"
	;;
	SunOS)
		if command -v gls >/dev/null 2>&1 ; then
			alias ls="gls -h --color=auto"
		elif ls --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias ls="ls -h --color=auto"
		else
			alias ls="ls -h"
		fi

		if command -v ggrep >/dev/null 2>&1 ; then
			alias grep='ggrep -d skip --color=auto'
		elif grep --version 2>/dev/null | grep GNU >/dev/null 2>&1 ; then
			alias grep='grep -d skip --color=auto'
		fi

		for locate in glocate slocate ; do
			command -v $locate >/dev/null 2>&1 && alias locate=$locate
		done
	;;
esac

if command -v gobjdump >/dev/null 2>&1 ; then
	alias objdump=gobjdump
fi

if command -v ack-grep >/dev/null 2>&1 ; then
	alias ack=ack-grep
fi

alias rgrep='grep -R -n --exclude=*.swp --exclude=.svn'
alias igrep='grep -i'

alias rm='rm -ir'
alias df='df -h'
alias du='du -h'
alias ping='ping -c4'
alias cp='cp -iR'
alias mv='mv -i'
alias rm='rm -ir'
alias mkdir='mkdir -p'
alias :q='exit'
alias :wq='exit'
alias inst='sudo yaourt -S'
alias xmoconf='vim ~/.xmonad/xmonad.hs'
alias lsd='ls -l | grep "^d"'
alias rezsh='source ~/.zshrc'
alias ll='ls -lh'
alias lla='ll -a'
alias la='ls -a'
alias svnstm='svn st | grep -v "^X" | grep -v "^Perf" | grep -v "^\?" | uniq'
alias svnst='svn st --ignore-externals | grep -v "^X"'
alias ......='cd ../../../../..'
alias .....='cd ../../../..'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias quickload="top -b -n1 | head -n1 | awk '{print $12, $13, $14}'"
alias sum="awk '{t+=\$1} END {print t}'"

alias cleandocker="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc:ro spotify/docker-gc"
alias nukedocker="docker ps -aq | xargs docker rm -f; docker images -aq | xargs docker rmi -f"
alias docker-logs-truncate='docker ps -q | while read cid; do echo > $(docker inspect --format="{{.LogPath}}" $cid); done'
alias prunedocker="docker system prune --volumes --all --force"
command -v time >/dev/null 2>&1 && alias time='command time'
alias git-branch-lasttouch='for k in `git branch | sed s/^..//`; do echo -e `git log -1 --pretty=format:"%Cgreen%ci %Cblue%cr%Creset" $k --`\\t"$k";done | sort'

alias getcert='echo | openssl s_client -servername NAME -connect'
alias certdate='openssl x509 -noout -dates'

alias mmaster='git fetch origin; git merge origin/master -m "MERGE: in origin/master"'
alias watchdot='watch dot -O -Tpng -Tsvg'

function checkcert() {
	getcert $1:443 | certdate
}

gdate &>/dev/null || alias gdate=date
function zdate() {
    gdate -u -Iseconds -d "${1-now}" | sed -e 's/[+-][:0-9]*$//'
}

function diffgroups() {
	diff -y <(groups $1 | tr ' ' '\n') <(groups $2 | tr ' ' '\n')
}

function make_gif() {
	rm -f /tmp/palette.png $2
	ffmpeg  -i "$1" -filter_complex "[0:v] palettegen" /tmp/palette.png
	ffmpeg -i "$1" -i /tmp/palette.png -filter_complex "[0:v][1:v] paletteuse" "$2"
}
