#!/usr/bin/python

import sys
import math

name = sys.argv[1].lower()

tableau = { 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8,
	'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16,
	'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24,
	'y': 25, 'z': 26, '0': 27, '1': 28, '2': 29, '3': 30, '4': 31, '5': 32,
	'6': 33, '7': 34, '8': 35, '9': 36 }

rtableau = 'abcdefghijklmnopqrstuvwxyz0123456789'

sym = [')', '!', '@', '#', '$', '%', '^', '&', '*', '(']

out = name[0].upper() + name[1] + str(tableau[name[2]] % 10) + \
	sym[abs(tableau[name[3]] - 4) % 10] + name[-1] + name[-2].upper() + \
	'L' + rtableau[(tableau[name[-3]] + 3 - 1) % len(rtableau)] + \
	'&' + 'm'

print out
